[greeter]
background=/usr/share/pixmaps/castleHalloween.jpeg
theme-name=Adwaita-dark
icon-theme-name=Papirus-Dark
cursor-theme-name=Qogir-Dark
cursor-theme-size=24
user-background=false

font-name=DejaVu Sans 11
xft-antialias=true
xft-hintstyle=slight
xft-rgba=rgb

hide-user-image=false
round-user-image=true
