#! /bin/sh

# workspaces (SPECIAL)
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config metge_overlaping_monitors true
"$HOME"/.config/bspwm/bin/monitorSetup

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# 2k setup
export GDK_SCALE=1
export GDK_DPI_SCALE=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTORS="1.25;1"
export QT_FONT_DPI=120

run() {
	if ! pidof -q "$1"; then
		"$@" &
	fi
}

# launch sxhkd daemon
run sxhkd -c "${HOME}"/.config/bspwm/config/sxhkdrc

# set a wallpaper
run feh --bg-fill /home/z0rxh/desktop/z0rxh/wallpapers/sword_women.jpg 

# set system vars for polybar
"$HOME"/.config/bspwm/bin/setSysVars

# load current theme
"${HOME}"/.config/bspwm/bin/theme.sh

# launch picom
run picom

# Never close the active monitors for inactivity
run xset s off
run xset -dpms
run xset s noblank

# Spanish keyboard layout
run setxkbmap es
